// React/src/App.js
import './App.css';
import { PdfViewerComponent, Toolbar, Magnification, Navigation, LinkAnnotation, BookmarkView, ThumbnailView, Print, TextSelection, TextSearch, Annotation, FormFields, FormDesigner, Inject, AjaxHandler } from '@syncfusion/ej2-react-pdfviewer';
import { ContextMenuComponent } from '@syncfusion/ej2-react-navigations';
import { useRef } from 'react';
function App() {
  const viewer = useRef(null);
  const menuItems = [
      { text: 'Rotate' },
      { text: 'Delete' },
      { text: 'Add' }
  ];
  const serviceUrl = 'https://localhost:7006/pdfviewer'; // .net 6.0
  //const serviceUrl = 'https://localhost:44356/pdfviewer'; //.net 5.0
  //const serviceUrl = 'https://localhost:44330/pdfviewer'; //.netcore 3.1
  const documentName = 'PDF_Succinctly.pdf';
  let isReload = false;
  let pageNumber = 0;
  function documentload() {
      if (isReload) {
        //Navigate to the page where the server side action is performed
        viewer.current.navigation.goToPage(pageNumber + 1);
        isReload = false;
      }
    };
  
    function menuSelect(args) {
      let action = args.item.text;
      pdfServerAction(action);
    }
  
    function pdfServerAction(action) {
      //Get the JSON Data of the download request to use in server side while getting the current PDF in the server-side
      let jsonData = (viewer.current.viewerBase ).constructJsonDownload();
      pageNumber = (viewer.current.viewerBase.activeElements ).activePage;
      if (pageNumber===null){return;}
      let fileName = viewer.current.fileName;
      //Send a Ajax request with download JSON data and the action name to perform the action in the server
      let RequestHandler = new AjaxHandler(viewer.current);
      RequestHandler.url = viewer.current.serviceUrl + '/' + 'PDFAction';
      jsonData['pageNumber'] = pageNumber;
      jsonData['action'] = action;
      jsonData['documentPath'] = fileName;
      RequestHandler.send(jsonData);
      RequestHandler.onSuccess =  (result) =>{
        //Reload the Updated PDF in the PDFViewer
        viewer.current.serverActionSettings.load = 'ReLoad';
        isReload = true;
        viewer.current.load(viewer.current.fileName, null)
        viewer.current.serverActionSettings.load = 'Load';
      };
    }
      return (<div>
      <div className='control-section'>
        <div style={{'height':"25px"}}>
      <button id="rotate" onClick={()=>pdfServerAction("Rotate")}>RotatePage</button>
      <button id="delete" onClick={()=>pdfServerAction("Delete")}>DeletePage</button>
      <button id="add" onClick={()=>pdfServerAction("Add")}>AddPage</button>
      </div>
        <div style={{'height':"calc(100vh - 25px)"}}>
      <ContextMenuComponent target="#pdfviewer" items={menuItems} select={menuSelect}/>
          <PdfViewerComponent ref={viewer} documentLoad={documentload} id="pdfviewer" contextMenuOption="None" documentPath={documentName} serviceUrl={serviceUrl} style={{ 'height': '100%' }}>
              <Inject services={[Toolbar, Magnification, Navigation, LinkAnnotation, BookmarkView, ThumbnailView, Print, TextSelection, TextSearch, Annotation, FormFields, FormDesigner]}/>
          </PdfViewerComponent>
          </div>
        </div>

      </div>);
}

export default App;

// Vue/src/App.vue
<template>
<div class='control-section'>
    <div style='height:"25px"'>
      <button id="rotate" @click="pdfServerAction('Rotate')"  >RotatePage</button>
      <button id="delete" @click="pdfServerAction('Delete')" >DeletePage</button>
      <button id="add" @click="pdfServerAction('Add')" >AddPage</button>
    </div>
    <div style='height:"calc(100vh - 25px)"'>
      <ejs-contextmenu target='#pdfViewer' :items='menuItems'  :select="menuSelect"></ejs-contextmenu>
      <ejs-pdfviewer id="pdfViewer" ref="viewer" :serviceUrl="serviceUrl" :documentPath="documentPath" :documentLoad="documentload"> </ejs-pdfviewer>
    </div>
  </div>
</template>

<script>
import { PdfViewerComponent, AjaxHandler, Toolbar, Magnification, Navigation, LinkAnnotation, BookmarkView, ThumbnailView, Print, TextSelection, TextSearch, Annotation, FormDesigner, FormFields } from '@syncfusion/ej2-vue-pdfviewer';

import { ContextMenuComponent } from "@syncfusion/ej2-vue-navigations";

export default {
  name: 'App',
  components: {
    "ejs-pdfviewer": PdfViewerComponent,
    "ejs-contextmenu": ContextMenuComponent
  },
  data () {
    return {
      serviceUrl: 'https://localhost:7006/pdfviewer', // .net 6.0
      //serviceUrl: 'https://localhost:44356/pdfviewer', //.net 5.0
      //serviceUrl: 'https://localhost:44330/pdfviewer', //.netcore 3.1
      documentPath:"PDF_Succinctly.pdf",
      isReload : false,
      pageNumber : 0,
      menuItems: [
          { text: 'Rotate' }, 
          { text: 'Delete' }, 
          { text: 'Add' }
        ]
    };
  },
  methods: {
    documentload: function () {
      if (this.isReload) {
        this.$refs.viewer.ej2Instances.navigation.goToPage(this.pageNumber + 1);
        this.isReload = false;
      }
    },

    menuSelect: function (args) {
      let action = args.item.text;
      this.pdfServerAction(action);
    },

    pdfServerAction: function (action) {
      let pdfViewerInstance = this.$refs.viewer.ej2Instances;
      let jsonData = pdfViewerInstance.viewerBase.constructJsonDownload();
      this.pageNumber = pdfViewerInstance.viewerBase.activeElements.activePage;	  
      if (this.pageNumber===null){return;}
      let fileName = pdfViewerInstance.fileName;
      let RequestHandler = new AjaxHandler(pdfViewerInstance);
      RequestHandler.url = pdfViewerInstance.serviceUrl + '/' + 'PDFAction';
      jsonData['pageNumber'] = this.pageNumber;
      jsonData['action'] = action;
      jsonData['documentPath'] = fileName;
      RequestHandler.send(jsonData);
      RequestHandler.onSuccess = () => {
        pdfViewerInstance.serverActionSettings.load = 'ReLoad';
        this.isReload = true;
        pdfViewerInstance.load(pdfViewerInstance.fileName, null);
        pdfViewerInstance.serverActionSettings.load = 'Load';
      };
    }
  },
  provide: {
    PdfViewer: [Toolbar, Magnification, Navigation, LinkAnnotation, BookmarkView, ThumbnailView, Print, TextSelection, TextSearch, Annotation, FormDesigner, FormFields]
  }
}
</script>

<style>
@import '../node_modules/@syncfusion/ej2-base/styles/material.css';
@import '../node_modules/@syncfusion/ej2-buttons/styles/material.css';
@import '../node_modules/@syncfusion/ej2-dropdowns/styles/material.css';  
@import '../node_modules/@syncfusion/ej2-inputs/styles/material.css';  
@import '../node_modules/@syncfusion/ej2-navigations/styles/material.css';
@import '../node_modules/@syncfusion/ej2-popups/styles/material.css';
@import '../node_modules/@syncfusion/ej2-splitbuttons/styles/material.css';
@import '../node_modules/@syncfusion/ej2-lists/styles/material.css';
@import '../node_modules/@syncfusion/ej2-vue-pdfviewer/styles/material.css';

#pdfViewer {
height: 640px;
}
</style>
