// React/src/App.js
import './App.css';
import { PdfViewerComponent, Toolbar, Magnification, Navigation, LinkAnnotation, BookmarkView, ThumbnailView, Print, TextSelection, TextSearch, Annotation, FormFields, FormDesigner, Inject, AjaxHandler } from '@syncfusion/ej2-react-pdfviewer';
import { ContextMenuComponent } from '@syncfusion/ej2-react-navigations';
import { useRef } from 'react';
function App() {
  const viewer = useRef(null);
  const menuItems = [
      { text: 'Rotate' },
      { text: 'Delete' },
      { text: 'Add' }
  ];
  const serviceUrl = 'https://localhost:7006/pdfviewer'; // .net 6.0
  //const serviceUrl = 'https://localhost:44356/pdfviewer'; //.net 5.0
  //const serviceUrl = 'https://localhost:44330/pdfviewer'; //.netcore 3.1
  const documentName = 'PDF_Succinctly.pdf';
  let isReload = false;
  let pageNumber = 0;
  function documentload() {
      if (isReload) {
        //Navigate to the page where the server side action is performed
        viewer.current.navigation.goToPage(pageNumber + 1);
        isReload = false;
      }
    };
  
    function menuSelect(args) {
      let action = args.item.text;
      pdfServerAction(action);
    }
  
    function pdfServerAction(action) {
      //Get the JSON Data of the download request to use in server side while getting the current PDF in the server-side
      let jsonData = (viewer.current.viewerBase ).constructJsonDownload();
      pageNumber = (viewer.current.viewerBase.activeElements ).activePage;
      if (pageNumber===null){return;}
      let fileName = viewer.current.fileName;
      //Send a Ajax request with download JSON data and the action name to perform the action in the server
      let RequestHandler = new AjaxHandler(viewer.current);
      RequestHandler.url = viewer.current.serviceUrl + '/' + 'PDFAction';
      jsonData['pageNumber'] = pageNumber;
      jsonData['action'] = action;
      jsonData['documentPath'] = fileName;
      RequestHandler.send(jsonData);
      RequestHandler.onSuccess =  (result) =>{
        //Reload the Updated PDF in the PDFViewer
        viewer.current.serverActionSettings.load = 'ReLoad';
        isReload = true;
        viewer.current.load(viewer.current.fileName, null)
        viewer.current.serverActionSettings.load = 'Load';
      };
    }
      return (<div>
      <div className='control-section'>
        <div style={{'height':"25px"}}>
      <button id="rotate" onClick={()=>pdfServerAction("Rotate")}>RotatePage</button>
      <button id="delete" onClick={()=>pdfServerAction("Delete")}>DeletePage</button>
      <button id="add" onClick={()=>pdfServerAction("Add")}>AddPage</button>
      </div>
        <div style={{'height':"calc(100vh - 25px)"}}>
      <ContextMenuComponent target="#pdfviewer" items={menuItems} select={menuSelect}/>
          <PdfViewerComponent ref={viewer} documentLoad={documentload} id="pdfviewer" contextMenuOption="None" documentPath={documentName} serviceUrl={serviceUrl} style={{ 'height': '100%' }}>
              <Inject services={[Toolbar, Magnification, Navigation, LinkAnnotation, BookmarkView, ThumbnailView, Print, TextSelection, TextSearch, Annotation, FormFields, FormDesigner]}/>
          </PdfViewerComponent>
          </div>
        </div>

      </div>);
}

export default App;

// Angular/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import {
  PdfViewerComponent, LinkAnnotationService, BookmarkViewService, MagnificationService, ThumbnailViewService,
  ToolbarService, NavigationService, TextSearchService, TextSelectionService, PrintService, AnnotationService, FormFieldsService, ContextMenuAction, AjaxHandler
} from '@syncfusion/ej2-angular-pdfviewer';
import { MenuEventArgs, MenuItemModel } from '@syncfusion/ej2-navigations';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  // tslint:disable-next-line:max-line-length
  providers: [LinkAnnotationService, BookmarkViewService, MagnificationService, ThumbnailViewService, ToolbarService, NavigationService, TextSearchService, TextSelectionService, PrintService, AnnotationService, FormFieldsService]
})
export class AppComponent {
  @ViewChild('pdfviewer')
  public viewer!: PdfViewerComponent;
  
  public service: string = 'https://localhost:7006/pdfviewer'; // .net 6.0
  //public service: string = 'https://localhost:44356/pdfviewer'; //.net 5.0
  //public service: string = 'https://localhost:44330/pdfviewer'; //.netcore 3.1

  public document: string = 'PDF_Succinctly.pdf';
  public menuItems: MenuItemModel[] =  [
    { text: 'Rotate' },
    { text: 'Delete' },
    { text: 'Add' }
  ];
  public contextMenuAction : ContextMenuAction ="None";
  private isReload:boolean = false;
  private pageNumber:number = 0;
  ngOnInit(): void {
      // ngOnInit function
  }

  public documentload():void {
    if (this.isReload) {
      //Navigate to the page where the server side action is performed
      this.viewer.navigation.goToPage(this.pageNumber + 1);
      this.isReload = false;
    }
  };

  public menuSelect(args:MenuEventArgs):void {
    let action:string = args.item.text as string;
    this.pdfServerAction(action);
  }

  public pdfServerAction(action: string):void {
    //Get the JSON Data of the download request to use in server side while getting the current PDF in the server-side
    let jsonData = (this.viewer.viewerBase as any).constructJsonDownload();
    this.pageNumber = (this.viewer.viewerBase.activeElements as any).activePage;
    if (this.pageNumber===null){return;}
    let fileName = this.viewer.fileName;
    //Send a Ajax request with download JSON data and the action name to perform the action in the server
    let RequestHandler = new AjaxHandler(this.viewer);
    RequestHandler.url = this.viewer.serviceUrl + '/' + 'PDFAction';
    jsonData['pageNumber'] = this.pageNumber;
    jsonData['action'] = action;
    jsonData['documentPath'] = fileName;
    RequestHandler.send(jsonData);
    RequestHandler.onSuccess =  (result: any) =>{
      //Reload the Updated PDF in the PDFViewer
      this.viewer.serverActionSettings.load = 'ReLoad';
      this.isReload = true;
      (this.viewer as any).load(this.viewer.fileName, null);
      this.viewer.serverActionSettings.load = 'Load';
    };
  }
}

<div class='control-section'>
  <div style='height:"25px"'>
    <button id="rotate" (click)="pdfServerAction('Rotate')"  >RotatePage</button>
    <button id="delete" (click)="pdfServerAction('Delete')" >DeletePage</button>
    <button id="add" (click)="pdfServerAction('Add')" >AddPage</button>
  </div>
  <div style='height:"calc(100vh - 25px)"'>
    <ejs-contextmenu id='contextmenu' target='#pdfViewer' (select)="menuSelect($event)" [items]= 'menuItems'></ejs-contextmenu>`
    <ejs-pdfviewer #pdfviewer id="pdfViewer" [serviceUrl]='service' [contextMenuOption]="contextMenuAction" [documentPath]='document' style="height:640px;display:block"
    (documentLoad)="documentload()"></ejs-pdfviewer>
  </div>
</div>
